# Generated by Django 4.2.1 on 2025-10-24 16:22

from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        default=monitor.models.gen_uuid,
                        editable=False,
                        max_length=32,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="摄像机名称"),
                ),
                (
                    "rtsp",
                    models.CharField(default="", max_length=150, verbose_name="rtsp"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="位置"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now=True, verbose_name="添加时间"),
                ),
                (
                    "is_active",
                    models.IntegerField(
                        choices=[(0, "offline"), (1, "online")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "db_table": "tb_camera",
                "ordering": ("-create_time",),
            },
        ),
    ]
